[versions]
antlr = "4.13.2"
bouncycastle = "1.83"
brotli = "1.16.0"
diffutils = "1.3.0"
flyway = "12.0.0"
graaljs = "25.0.2"
jbrofuzz = "2.5.1"
jsoup = "1.22.1"
kotlin = "1.3.72"
langchain4j = "1.10.0"
log4j = "2.25.2"
nanohttpd = "2.3.1"
netty = "4.1.100.Final"
re2j = "1.8"
slf4j = "2.0.17"

[libraries]
ascanrules-procyonCompilerTools = "org.bitbucket.mstrobel:procyon-compilertools:0.6.0"
ascanrules-rhino = "org.mozilla:rhino:1.9.0"
ascanrulesBeta-diffutils = { module = "com.googlecode.java-diff-utils:diffutils", version.ref = "diffutils" }
ascanrulesBeta-jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
authhelper-otpJava = "com.github.bastiaanjansen:otp-java:2.1.0"
beanshell-beanshell = "org.beanshell:bsh:2.0b5"
bugtracker-bridgeMethodAnnotations = "com.infradna.tool:bridge-method-annotation:1.24"
bugtracker-githubApi = "org.kohsuke:github-api:1.330"
bugtracker-j2bugzilla = "com.j2bugzilla:j2bugzilla:2.2.1"
callgraph-jgraphx = "org.tinyjee.jgraphx:jgraphx:3.4.1.3"
commonlib-apache-commons-collections4 = "org.apache.commons:commons-collections4:4.5.0"
commonlib-apache-commons-csv = "org.apache.commons:commons-csv:1.14.1"
commonlib-apache-commons-io = "commons-io:commons-io:2.21.0"
commonlib-jackson-bom = "com.fasterxml.jackson:jackson-bom:2.21.0"
commonlib-jackson-databind.module = "com.fasterxml.jackson.core:jackson-databind"
commonlib-jackson-dataformat-xml.module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml"
commonlib-jackson-dataformat-yaml.module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml"
commonlib-jackson-datatype-jdk8.module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8"
commonlib-jackson-datatype-jsr310.module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"
database-datanucleusJdo = "org.datanucleus:datanucleus-accessplatform-jdo-rdbms:6.0.10"
database-flywayCore = { module =  "org.flywaydb:flyway-core", version.ref = "flyway" }
database-flywayDatabaseHsqldb =  { module = "org.flywaydb:flyway-database-hsqldb", version.ref = "flyway" }
database-sqliteJdbc = "org.xerial:sqlite-jdbc:3.51.1.0"
diff-diffutils = { module = "com.googlecode.java-diff-utils:diffutils", version.ref = "diffutils" }
exim-harReader = "de.sstoehr:har-reader:3.1.6"
exim-hektorFsm = "io.hektor:hektor-fsm:0.0.8"
fuzz-jbrofuzzCore = { module = "org.owasp.jbrofuzz:jbrofuzz-core", version.ref = "jbrofuzz" }
fuzz-rgxgen = "com.github.curious-odd-man:rgxgen:3.1"
fuzz-snodge = "com.natpryce:snodge:2.1.2.2"
graaljs-graaljs = { module = "org.graalvm.js:js-community", version.ref = "graaljs" }
graaljs-jsScriptEngine = { module = "org.graalvm.js:js-scriptengine", version.ref = "graaljs" }
graphql-graphqlJava = "com.graphql-java:graphql-java:25.0"
groovy-groovy = "org.apache.groovy:groovy-all:5.0.4"
grpc-protobuf = "io.grpc:grpc-protobuf:1.78.0"
imagelocationscanner-metadataExtractor = "com.drewnoakes:metadata-extractor:2.19.0"
jruby-jruby = "org.jruby:jruby-complete:9.4.14.0"
jython-jython = "org.python:jython-standalone:2.7.4"
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-scripting = { module = "org.jetbrains.kotlin:kotlin-scripting-jsr223-embeddable", version.ref = "kotlin" }
kotlin-stdlibJdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
llm-langchain4j = { module = "dev.langchain4j:langchain4j", version.ref = "langchain4j" }
llm-langchain4j-azureOpenAi = { module = "dev.langchain4j:langchain4j-azure-open-ai", version.ref = "langchain4j" }
llm-langchain4j-ollama = { module = "dev.langchain4j:langchain4j-ollama", version.ref = "langchain4j" }
llm-langchain4j-googleGemini = { module = "dev.langchain4j:langchain4j-google-ai-gemini", version.ref = "langchain4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }
log4j-slf4j2 = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
network-bouncycastle-bcmail = { module = "org.bouncycastle:bcmail-jdk18on", version.ref = "bouncycastle" }
network-bouncycastle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }
network-bouncycastle-bcprov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
network-brotli = { module = "com.aayushatharva.brotli4j:brotli4j", version.ref = "brotli" }
network-brotli-linux-amd64 = { module = "com.aayushatharva.brotli4j:native-linux-x86_64", version.ref = "brotli" }
network-brotli-osx-aarch64 = { module = "com.aayushatharva.brotli4j:native-osx-aarch64", version.ref = "brotli" }
network-brotli-osx-amd64 = { module = "com.aayushatharva.brotli4j:native-osx-x86_64", version.ref = "brotli" }
network-brotli-windows-amd64 = { module = "com.aayushatharva.brotli4j:native-windows-x86_64", version.ref = "brotli" }
network-httpclient = "org.apache.httpcomponents.client5:httpclient5:5.2.1"
network-ice4j = "org.jitsi:ice4j:3.0-24-g34c2ce5"
network-netty-codec = { module = "io.netty:netty-codec", version.ref = "netty" }
network-netty-codec-http2 = { module = "io.netty:netty-codec-http2", version.ref = "netty" }
network-netty-handler = { module = "io.netty:netty-handler", version.ref = "netty" }
openapi-swagger-compatSpecParser = "io.swagger:swagger-compat-spec-parser:1.0.75"
openapi-swagger-parser = "io.swagger.parser.v3:swagger-parser:2.1.37"
pscanrules-antlr = { module = "org.antlr:antlr4", version.ref = "antlr" }
pscanrules-antlr-runtime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr" }
pscanrules-htmlunit-csp = "org.htmlunit:htmlunit-csp:4.21.0"
pscanrules-re2j = { module = "com.google.re2j:re2j", version.ref = "re2j" }
pscanrulesAlpha-re2j = { module = "com.google.re2j:re2j", version.ref = "re2j" }
reports-flyingSaucerPdf = "org.xhtmlrenderer:flying-saucer-pdf:9.13.3"
reports-thymeleaf = "org.thymeleaf:thymeleaf:3.1.3.RELEASE"
saml-jaxbRuntime = "org.glassfish.jaxb:jaxb-runtime:4.0.6"
scripts-byteBuddy = "net.bytebuddy:byte-buddy:1.18.4"
selenium-htmlunit3Driver = "org.seleniumhq.selenium:htmlunit3-driver:4.34.0"
selenium-seleniumJava = "org.seleniumhq.selenium:selenium-java:4.40.0"
soap-jakartaXmlSoapApi = "jakarta.xml.soap:jakarta.xml.soap-api:3.0.2"
soap-saajImpl = "com.sun.xml.messaging.saaj:saaj-impl:3.0.4"
soap-soaModelCore = "com.predic8:soa-model-core:2.2.0"
spider-kaitaiStructRuntime = "io.kaitai:kaitai-struct-runtime:0.11"
spiderAjax-apache-commons-math = "commons-math:commons-math:1.2"
spiderAjax-findBugsAnnotations = "com.google.code.findbugs:jsr305:3.0.2"
spiderAjax-guiceAssistedInject = "com.google.inject.extensions:guice-assistedinject:6.0.0"
spiderAjax-jcipAnnotations = "net.jcip:jcip-annotations:1.0"
spiderAjax-julToSlf4j = { module = "org.slf4j:jul-to-slf4j", version.ref = "slf4j" }
spiderAjax-metricsCore = "com.codahale.metrics:metrics-core:3.0.2"
spiderAjax-nekohtml = "net.sourceforge.nekohtml:nekohtml:1.9.22"
spiderAjax-xmlunit = "xmlunit:xmlunit:1.6"
sqliplugin-jdom = "org.jdom:jdom:2.0.2"
test-hamcrest = "org.hamcrest:hamcrest-library:3.0"
test-junit-jupiter = "org.junit.jupiter:junit-jupiter:6.0.2"
test-junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
test-mockito-junit-jupiter = "org.mockito:mockito-junit-jupiter:5.21.0"
test-selenium-jupiter = "io.github.bonigarcia:selenium-jupiter:5.1.1"
test-webdrivermanager = "io.github.bonigarcia:webdrivermanager:5.7.0"
testutils-httpclient5 = "org.apache.httpcomponents.client5:httpclient5:5.2.1"
testutils-nanohttpd-webserver = { module = "org.nanohttpd:nanohttpd-webserver", version.ref = "nanohttpd" }
testutils-nanohttpd-websocket = { module = "org.nanohttpd:nanohttpd-websocket", version.ref = "nanohttpd" }
testutils-zap = "org.zaproxy:zap:2.17.0"
wappalyzer-jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
wappalyzer-jsvg = "com.github.weisj:jsvg:2.0.0"
wappalyzer-re2j = { module = "com.google.re2j:re2j", version.ref = "re2j" }
zest-jbrofuzzCore = { module = "org.owasp.jbrofuzz:jbrofuzz-core", version.ref = "jbrofuzz" }
zest-zest = "org.zaproxy:zest:0.35.0"

[plugins]
cyclonedx = "org.cyclonedx.bom:2.2.0"
datanucleus = "org.rm3l.datanucleus-gradle-plugin:2.0.0"
dependencyUpdates = "com.github.ben-manes.versions:0.53.0"
errorprone = "net.ltgt.errorprone:5.0.0"
japicmp = "me.champeau.gradle.japicmp:0.4.6"
lombok = "io.freefair.lombok:9.2.0"
sonarqube = "org.sonarqube:7.2.2.6593"
spotless.id = "com.diffplug.spotless"
undercouch-download = "de.undercouch.download:5.7.0"
zaproxy-addon = "org.zaproxy.add-on:0.13.1"
zaproxy-common = "org.zaproxy.common:0.5.0"
zaproxy-crowdin = "org.zaproxy.crowdin:0.6.0"
